// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojrkdrepeiifsgmszfgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcmtkcmVwZWlpZnNnbXN6ZmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODA3NjAsImV4cCI6MjA3NDM1Njc2MH0.K6eoEMva3oJ8GVEjhTYfWd9SaSYn4gOziDHBzEuR_70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});